# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipAddress.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ipAddress.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fipAddress.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\xcd\x02\n\tIpAddress\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\r\n\x05owner\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\nis_gateway\x18\x05 \x01(\x08\x12\x10\n\x08hostname\x18\x06 \x01(\t\x12\x1a\n\x08state_id\x18\x07 \x01(\x0e\x32\x08.StateId\x12-\n\tlast_seen\x18\x0e \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rlast_modified\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x30\n\x0c\x64\x61te_created\x18\x10 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tsubnet_id\x18\x11 \x01(\t\x12\x13\n\x0bmac_address\x18\x12 \x01(\t\"V\n\x10IpAddressRequest\x12\x0c\n\x02id\x18\x01 \x01(\tH\x00\x12\x0e\n\x04name\x18\x02 \x01(\tH\x00\x12\x13\n\tsubnet_id\x18\x03 \x01(\tH\x00\x42\x0f\n\rrequest_field\"3\n\x11IpAddressResponse\x12\x1e\n\nip_address\x18\x01 \x03(\x0b\x32\n.IpAddress2\xee\x01\n\x10IpAddressService\x12\x39\n\x10GetIpAddressById\x12\x11.IpAddressRequest\x1a\x12.IpAddressResponse\x12.\n\x0c\x41\x64\x64IpAddress\x12\n.IpAddress\x1a\x12.IpAddressResponse\x12\x31\n\x0fUpdateIpAddress\x12\n.IpAddress\x1a\x12.IpAddressResponse\x12<\n\x13\x44\x65leteIpAddressById\x12\x11.IpAddressRequest\x1a\x12.IpAddressResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipAddress_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IPADDRESS']._serialized_start=67
  _globals['_IPADDRESS']._serialized_end=400
  _globals['_IPADDRESSREQUEST']._serialized_start=402
  _globals['_IPADDRESSREQUEST']._serialized_end=488
  _globals['_IPADDRESSRESPONSE']._serialized_start=490
  _globals['_IPADDRESSRESPONSE']._serialized_end=541
  _globals['_IPADDRESSSERVICE']._serialized_start=544
  _globals['_IPADDRESSSERVICE']._serialized_end=782
# @@protoc_insertion_point(module_scope)
