# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ipAddress_pb2 as ipAddress__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ipAddress_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IpAddressServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIpAddressById = channel.unary_unary(
                '/IpAddressService/GetIpAddressById',
                request_serializer=ipAddress__pb2.IpAddressRequest.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                _registered_method=True)
        self.AddIpAddress = channel.unary_unary(
                '/IpAddressService/AddIpAddress',
                request_serializer=ipAddress__pb2.IpAddress.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                _registered_method=True)
        self.UpdateIpAddress = channel.unary_unary(
                '/IpAddressService/UpdateIpAddress',
                request_serializer=ipAddress__pb2.IpAddress.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                _registered_method=True)
        self.DeleteIpAddressById = channel.unary_unary(
                '/IpAddressService/DeleteIpAddressById',
                request_serializer=ipAddress__pb2.IpAddressRequest.SerializeToString,
                response_deserializer=ipAddress__pb2.IpAddressResponse.FromString,
                _registered_method=True)


class IpAddressServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIpAddressById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddIpAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIpAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIpAddressById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IpAddressServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIpAddressById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIpAddressById,
                    request_deserializer=ipAddress__pb2.IpAddressRequest.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'AddIpAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.AddIpAddress,
                    request_deserializer=ipAddress__pb2.IpAddress.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'UpdateIpAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIpAddress,
                    request_deserializer=ipAddress__pb2.IpAddress.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
            'DeleteIpAddressById': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIpAddressById,
                    request_deserializer=ipAddress__pb2.IpAddressRequest.FromString,
                    response_serializer=ipAddress__pb2.IpAddressResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'IpAddressService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('IpAddressService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IpAddressService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIpAddressById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IpAddressService/GetIpAddressById',
            ipAddress__pb2.IpAddressRequest.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddIpAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IpAddressService/AddIpAddress',
            ipAddress__pb2.IpAddress.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIpAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IpAddressService/UpdateIpAddress',
            ipAddress__pb2.IpAddress.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIpAddressById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/IpAddressService/DeleteIpAddressById',
            ipAddress__pb2.IpAddressRequest.SerializeToString,
            ipAddress__pb2.IpAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
